# 项目相关配置
luna:
  hello:
    prefix: luna
    suffix: hello
  # 名称
  name: Luna
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/Luna/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 日志配置
logging:
  config: classpath:log/logback.xml

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    # 指定配置环境
    active: dev

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  #邮箱操作
  mail:
    username: 1173282254@qq.com
    password: udbxadzstgldhbeh
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.luna.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





